name: Nuitka Build on Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.10.0
        environment-file: environment.yml
        activate-environment: beamshapy-gui

    - name: Activate Conda Environment and Install Nuitka
      run: |
        conda activate beamshapy-gui
        python -m pip install --upgrade pip
        pip install nuitka

    - name: Compile with Nuitka
      run: |
        conda activate beamshapy-gui
        python -m nuitka main.py --show-progress --onefile --debug --enable-plugin=pyqt5 --include-data-file=./logo_beam_shaper.png=./icon/logo_beam_shaper.png

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Compiled-App
        path: main.exe 
